### ISSUE TITLE
GoogleImageDirectLink breaks video search

### ISSUE THREAD

**Issue by Lorentz83** [Lorentz83/userscripts#10]
Using google video search, the link on the video preview is overwritten to 
`https://www.google.com/undefined`

Example page:
https://www.google.com/search?q=funny+pet&bih=859&tbm=vid

See [comment](https://greasyfork.org/en/forum/discussion/comment/23301/#Comment_23301)

**Comment by ghost** [comment]
replacing line 138 with
`if ((as[0].href != '') && (! as[0].href.endsWith('#'))) {`
"fixes" it
