### ISSUE TITLE
Google Images direct link does not work on Google Hongkong

### ISSUE THREAD

**Issue by 775405984** [Lorentz83/userscripts#12]
https://www.google.com.hk/

**Comment by 775405984** [comment]
or any other country site

**Comment by Lorentz83** [comment]
Hi, 
I'm sorry for this very late reply. But for some reason I lost the notification email. 
As I wrote on [greasyfork](https://greasyfork.org/en/scripts/3187-google-images-direct-link), I cannot work on this script any more. 
I'll update the description also here.
