### ISSUE TITLE
Google Images direct link outputs TypeError to the console

### ISSUE THREAD

**Issue by alexolog** [Lorentz83/userscripts#2]
Google Images direct link outputs "TypeError: link.split is not a function" to the console
Sample url: http://tinyurl.com/qgoobg9

**Comment by Lorentz83** [comment]
I don't see any error. Do you have any other script or extension that may interfere? Otherwise we may be in the middle of a google update.
Is there anything else that doesn't work?

**Comment by alexolog** [comment]
seems to be working now.  Sorry for the false alarm

**Comment by Lorentz83** [comment]
No problem
