### ISSUE TITLE
Couldn't use the Show sizes feature in latest version 

### ISSUE THREAD

**Issue by 775405984** [Lorentz83/userscripts#4]
@Lorentz83 
![screenshot_2](https://cloud.githubusercontent.com/assets/7196377/13852945/801bf046-ec9f-11e5-8d6f-b2d1fd2fc470.png)

here is something I found, hope it helps.

https://stenevang.wordpress.com/2013/02/22/google-search-url-request-parameters/

**Comment by 775405984** [comment]
ever since 5.4c, 5.4b works fine.

**Comment by Lorentz83** [comment]
I wasn't aware of this function. It is lucky it worked in the older versions. 
Same problem if you specify a time range.
It shouldn't be too difficult to fix, hopefully I can release an update in the next days. 
Thank you for the report

**Comment by Lorentz83** [comment]
fixed in 6.1
