### ISSUE TITLE
Search by Image error in Google Images direct link 7.1

### ISSUE THREAD

**Issue by 775405984** [Lorentz83/userscripts#9]
When I try search by image, the thumbnail link always replaced by this:

https://www.google.com/undefined

![screenshot_1](https://cloud.githubusercontent.com/assets/7196377/14939839/1caef3d2-0f8b-11e6-9661-88a506761481.png)

P.S. could you develop a userscript that replace search engine results with direct link? THX

**Comment by Lorentz83** [comment]
Hi, 
can you give me the link of the search? Visually similar search works correctly for me. Therefore either you do a different kind of search (i.e. some extra parameters I didn't try) or you are using a localized version of google image which returns a different html that my script cannot understand.

**Comment by 775405984** [comment]
https://www.google.com/search?tbs=sbi:AMhZZisHFvhahxa4lZzfna9s_14UmNVpuufWhfgBq6AjFVN6QRwS9h22ljpuokSlwPYq5Ru5J4nhVF7RJsryzy2vG_1lQGo84fdxkC5VmYcD2v5mfPrMdXCs6OU3W4icNbZb9LqJuRY6zkl1b1ESupNwKtjBXAELZRdw2kPiPNpp3VFtCQYXfcO9VvnF3JwSD3rSg0C-xaoilHJiAY9kqEXfow1ns_1eEhX0VrTg9Whm8ELGzvaa8Tklu3TVok3f5rfaAtqZ3JHfUYsWFHgt5J0hy6jdE2WMa1bMqOR3eAAqgCbEJmvqEA0ZoUwNrfFgZUUOJqZoU20QTMFjaFtt-NdaHhfjWfbYloZJu-O9GnBdxre7b0pS9Mo9yH9aRf81VZ_16JQK0NGD_1SMj-c9zP1Q_1-PBAdzXEg_1i_11weM1-_1OIx6iwgZbJU9FBiJ9ZPTDRJeEIooKuYdYbyGyZeWowjH0BWPvha-aybQ2y2ZRgqe1up3uMDK9-nKaatHbZVVmrprIdMHYtNQxVltP3O6RQRB9XUjEJ9m2JRdMSGvtYgWRcQEI7N_1-pV6vWvMUoZaY0XZd7moVKQWHwZsGvcJR_15OR0q6JIJZorI-BU4hvrOj0Gm_1zaf8lV_1L_1IhkiU_1cnPHe5WbG5tAXXSmOU3tPiZFnC3CvT6HcjKYizVuU8yndewq93_1WqU14662-4KdmTJo7zimkzwGEIF4_1YXWrCyoan_1ymnoqmWLonTqWO2NeAzplU9x3wumtFYqauNvhy6cIFTVjO0IF3XPvAfYmKxJdt9riMK7mSxIvNtFvvG-mv_1xzqVa4jv-5IHoZIALyEkJ4hZuHZN0yBNLceqQXsMIzirNMdv_1ljaqeTYv1xKytRhdRicd5H1qt3qhdypEoBT8iBkmDg5OU7JUZ-a3gFa88HJ1O6uod025qNovexW3kHa_1UKeVrOgIFZuY3WaJQXgMIYHcRXQPj6h7a1NzLORtTYDBLgpmuLrNo-0jbLGN06M4fVtWxd996iGaJHoNIm11mqgkMMIf7onTEtQgRtq9x9l8VqvXVkxjiCj4i79XNtAsit7TQO29r2evCe0WL2OIoNMl8h4SZpgRpjoSBXpymm6BkAn1YiIqfqAugJNBg-iExHI33BKG0omU4iK7dfa3XGLRjOvDiNfBnk8Fq0pY-t_1k68BIogbdIxsZ4WMvl8kJsycm0X_1UtheIzulWWBBEn7rElC8a4v6o2olTlsftBM-mYUDgQqqosLgnRmK6EClbk_18WUZNDyPplVZWPrIuzyu9vWzxLJq0JGUgK0WIsEh4aHmALalUtD5tK2KhmLCaiv3reXC133oQ4y9GeoJ-FYWERh9Db62iGhn_1NUyb4bb4IR69i7msIkn4gU4n_1R_1u1KeGe4KyDk8jNtCIxN9G1UdYPlj9DYVhPwNvJxIqM3qUF4mrkWc1HLrJquUCdlmLGKUI8hzhD0ry1US5mcI2etkozaiJ_1BeDsOFqulWJLJ4k3i7oScV6y-TTTXcWxDbGJDxXCXukWdg29wgox_1WFguccdQHhWtoM-sWIay-ZIiHoGjjYHLPZWhJKT3YZ2zWulkCmGKVP-bMR_1AXPSEzSDlbaFGiDONV8nDRSG62KybDS_1E1BAMarhLgnIYSG4gRqyR17qOL6Ybd0s6YeFm0YkDYVddu_109bFDH77LXQf3xE7au-86hBaRswkm27BCvQ7yD6H0PpUkv1KlnZk&width=460&height=479
